### ISSUE TITLE
Support TestNG

### ISSUE THREAD

**Issue by artgo** [jadler-mocking/jadler#118]
Unfortunately when trying to run tests in TestNG we get an error:

FAILED CONFIGURATION: @BeforeMethod setup
java.lang.IllegalStateException: Jadler has not been initialized yet.
	at net.jadler.Jadler.checkInitialized(Jadler.java:764)
	at net.jadler.Jadler.port(Jadler.java:737)
	at com.appkong.combinator.services.WebAPIServiceIT.setup(WebAPIServiceIT.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

**Comment by jandudek** [comment]
Hi @artgo, thank you for the bug report! Could you please post here a minimal example code (some failing testng code plus a mvn/gradle configuration) to reproduce it?

**Comment by artgo** [comment]
Here you go:

```
  @BeforeMethod
   public void setup() {
         initJadler();
     }
```

It fails right there.

**Comment by jandudek** [comment]
I'm having a hard time reproduce this issue. I created this test using TestNG:

`
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import static net.jadler.Jadler.*;
import static org.junit.Assert.assertTrue;

public class NGTest {

    @BeforeMethod
    public void before() {
        System.out.println("before method");
        initJadler();
    }

    @Test
    public void testSomething() {
        System.out.println("test method");
        assertTrue(port() > 0);
    }
}
`

And it works correctly, the test method passes successfully. Here are the mvn dependencies:

`
    <dependencies>   
        <dependency>
            <groupId>net.jadler</groupId>
            <artifactId>jadler-all</artifactId>
            <version>1.3.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.10</version>
            <scope>test</scope>
        </dependency>     
    </dependencies>
`

Could you please provide a complete example of a failing TestNG test so I can investigate further?

**Comment by artgo** [comment]
I think our dependencies was wrong, since there is no other differences in our code.

**Comment by jandudek** [comment]
So can we close this issue now? Jadler seems to work with TestNG.

**Comment by artgo** [comment]
yep
